name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create config with...
        2. Run command...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration File
      description: Please paste the configuration file that causes the issue (if applicable)
      render: json

  - type: textarea
    id: output
    attributes:
      label: Command Output
      description: Full output from the sink command
      render: shell

  - type: input
    id: version
    attributes:
      label: Sink Version
      description: Output of `sink version`
      placeholder: "sink version 0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Alpine)
        - Linux (Other)
        - Windows
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: "e.g., macOS 14.1, Ubuntu 22.04, etc."
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
