name: Documentation Issue
description: Report missing, incorrect, or unclear documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      options:
        - README.md
        - examples/README.md
        - examples/USAGE.md
        - Code comments/docstrings
        - JSON schema documentation
        - Help command output
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: "File path or URL where the issue exists"
      placeholder: "examples/README.md, line 45"
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong
      description: Describe the documentation issue
      placeholder: The documentation says X, but it should say Y because...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
